### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Kadantte** [Ervie/Seiyuu.moe#14]
I created a blank database but I get this Error!
```shell
2020-08-15 10:08:02 Internal Error: SqliteException, Message: SQLite Error 1: 'no such table: Anime'., stack trace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at SeiyuuMoe.Infrastructure.Animes.AnimeRepository.GetOrderedPageByPopularityAsync(Expression`1 predicate, Int32 page, Int32 pageSize) in X:\DEV\Seiyuu.moe\API\SeiyuuMoe.Infrastructure\Animes\AnimeRepository.cs:line 73
   at SeiyuuMoe.Application.Animes.SearchAnime.SearchAnimeQueryHandler.HandleAsync(SearchAnimeQuery query) in X:\DEV\Seiyuu.moe\API\SeiyuuMoe.Application\Animes\SearchAnime\SearchAnimeQueryHandler.cs:line 29
   at SeiyuuMoe.API.Controllers.AnimeController.<>c__DisplayClass5_0.<<GetSearchEntries>b__0>d.MoveNext() in X:\DEV\Seiyuu.moe\API\SeiyuuMoe.API\Controllers\AnimeController.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at SeiyuuMoe.API.Controllers.Base.BaseController.Handle(Func`1 func) in X:\DEV\Seiyuu.moe\API\SeiyuuMoe.API\Controllers\Base\BaseController.cs:line 25
2020-08-15 10:08:02 Internal Error: SqliteException, Message: SQLite Error 1: 'no such table: Anime'., stack trace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at SeiyuuMoe.Infrastructure.Animes.AnimeRepository.GetOrderedPageByPopularityAsync(Expression`1 predicate, Int32 page, Int32 pageSize) in X:\DEV\Seiyuu.moe\API\SeiyuuMoe.Infrastructure\Animes\AnimeRepository.cs:line 73
   at SeiyuuMoe.Application.Animes.SearchAnime.SearchAnimeQueryHandler.HandleAsync(SearchAnimeQuery query) in X:\DEV\Seiyuu.moe\API\SeiyuuMoe.Application\Animes\SearchAnime\SearchAnimeQueryHandler.cs:line 29
   at SeiyuuMoe.API.Controllers.AnimeController.<>c__DisplayClass5_0.<<GetSearchEntries>b__0>d.MoveNext() in X:\DEV\Seiyuu.moe\API\SeiyuuMoe.API\Controllers\AnimeController.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at SeiyuuMoe.API.Controllers.Base.BaseController.Handle(Func`1 func) in X:\DEV\Seiyuu.moe\API\SeiyuuMoe.API\Controllers\Base\BaseController.cs:line 25
```

If you don't mind can you please tell me how to create one for this project or you provide me with a Blank one!

**Comment by Ervie** [comment]
Hello,

I added schema sql to repo - you can find it here https://github.com/Ervie/Seiyuu.moe/blob/master/API/Schema.sql. When you execute it in your empty db, you just point to that file in the appsettings. I you like, I can even share dump from backup db.

I don't have time to develop this project lately, but one of the first things that I would like to to do is to refactor database part (migrations, few changes in schema, possible change to either MySQL or PostgreSQL). With migrations it would be much easier.

**Comment by Kadantte** [comment]
Oh if you share dump from backup db it will be great anyway thank's for the reply :D

**Comment by Ervie** [comment]
Hey, here's a link: https://bartlomiejbuchala.com/Files/dump.zip

I will remove the file later.

**Comment by Ervie** [comment]
Resolvefd for now; the file will be removed later

**Comment by Kadantte** [comment]
thanks for the file!
